const countries = [
  "Finland",
  "Denmark",
  "Sweden",
  "Norway",
  "Iceland",
  "Estonia",
  "Greece",
  "Ireland",
  "Latvia",
  "Lithuania",
  "Poland",
  "Slovakia",
  "Slovenia",
  "Ukraine",
  "Belarus",
  "Belgium",
  "Bosnia and Herzegovina",
  "Bulgaria",
  "Croatia",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Estonia",
  "Faroe Islands",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hungary",
  "Iceland",
  "Ireland",
  "Italy",
  "Kosovo",
  "Latvia",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Moldova",
  "Monaco",
  "Montenegro",
  "Netherlands",
  "North Macedonia",
  "Norway",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Sweden",
  "Switzerland",
  "Ukraine",
  "United Kingdom",
  "Vatican City",
];
const countriesWithLand = countries.filter((country) =>
  country.includes("land")
);
console.log(countriesWitIa);
const countriesWithLand2 = countries.filter((country) =>
  country.toLowerCase().includes("ia")
);
